---
# Pipelines variables

name: AdjustVM_$(Changenummer)
pr: none # will disable PR builds (but not CI builds)

variables:
- name: VSTS_ARM_REST_IGNORE_SSL_ERRORS
  value: true
- name: generic_branch 
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    value: main
  ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    value: dev

stages:
  - stage: TEST_CPUMEM
    condition: and(eq(variables['test'], 'true' ), ne(variables['Build.SourceBranchName'], 'main'), ne(variables['form_cpu'], ''), ne(variables['form_memory'], '') )   
    jobs:
    - template: Templates/run_AdjustMemoryCPU.yaml 
      parameters:
        ado_targetplatform: 'test'
        topdesk_environment: 'dev'
  - stage: DTAP_CPUMEM
    condition: and( eq(variables['test'], 'false' ) , eq(variables['Build.SourceBranchName'], 'main'), ne(variables['form_cpu'], ''), ne(variables['form_memory'], '') )
    jobs:
    - template: Templates/run_AdjustMemoryCPU.yaml
      parameters:
        ado_targetplatform: 'dtap'
        topdesk_environment: 'prd'
  - stage: TEST_SNAPSHOT
    condition: and(eq(variables['test'], 'true' ), ne(variables['Build.SourceBranchName'], 'main'), contains(variables['form_snapshot_type'], 'Snapshot') )   
    jobs:
    - template: Templates/run_Snapshot.yaml 
      parameters:
        ado_targetplatform: 'test'
        topdesk_environment: 'dev'
  - stage: DTAP_SNAPSHOT
    condition: and( eq(variables['test'], 'false' ) , eq(variables['Build.SourceBranchName'], 'main'), contains(variables['form_snapshot_type'], 'Snapshot') )
    jobs:
    - template: Templates/run_Snapshot.yaml
      parameters:
        ado_targetplatform: 'dtap'
        topdesk_environment: 'prd'