---
parameters:
  - name: ado_targetplatform
  - name: environment

jobs:
  - job:
    displayName: Trigger Template Deployment on ${{ parameters.ado_targetplatform }}
    timeoutInMinutes: 0 # Forever on on-premises agents
    pool:
      name: 'RadboudUMC On-premise Linux'
    steps:
      - checkout: self

      - script: packer init .
        workingDirectory: Packer/Win2019
        displayName: Packer init

      - script: packer validate -var-file="tst.pkrvars.hcl" -syntax-only .
        workingDirectory: Packer/Win2019
        displayName: Validate

      - script: |
          packer build -on-error=abort \
            -var-file="tst.pkrvars.hcl" \
            --var vsphere_user=$(vcusername) \
            --var vm_name=$(VMname) \
            .
        workingDirectory: Packer/Win2019
        displayName: Build